### ISSUE TITLE
How to deal with it after uploading?

### ISSUE THREAD

**Issue by Marow** [IzzySoft/virustotal#1]
Hi, 

how to deal with that tool after uploading a file and its checking?
What do to than? I only want clean files so i will wait or something?

**Comment by IzzySoft** [comment]
The initial call should either already return results, or the file is "queued for scan". In each case, the result contains a hash which you can use to obtain the result when it's available.

So as the example in the `README.md` shows:

* if it returns `1` results are available and `$vt->getResponse();` will obtain them
* if it returns `0`, the file is still queued and you need to call again later

Details on how the response looks like, as again the `README.md` explains, can be found in the [VirusTotal API documentation](https://www.virustotal.com/de/documentation/public-api/). So if you want only clean files, the field `positives` should be `0`. In all other cases, some engine reported a finding. Which doesn't necessarily need to be a virus; e.g. WhiteArmor quite often reports "PUP" (Potentially Unwanted Program) which according to my experience mostly can be ignored.
